source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLXCoreBluetooth_Example' do
  pod 'PLXCoreBluetooth', :path => '../'
end

target 'PLXCoreBluetooth_Tests' do
  pod 'PLXCoreBluetooth', :path => '../'
  pod 'Specta'
  pod 'Expecta'
end
